{"Director": {
  # "Worldmodel": 
  # {"datapath": "/home/jorgen/MoJo/hierarchical/data/worldmodel/",
  #  "modelfile": "/home/jorgen/MoJo/hierarchical/weights/worldmodel.pth",
  # "input_dim": 14400,
  #  "hid1_dim": 2048,
  #   "hid2_dim": 128,
  #   "latent_dim": 8,
  #   "lr": 0.001}, 
  "Manager": {"eps_clip": 0.2, "gamma": 0.99, "lr_actor": 3e-05, "lr_critic": 0.0001, "state_dim": 14400, "action_dim": 6, "K_epochs": 4, "action_std": 0.5, "has_continuous_action_space": false}, 
  "Worker": {"eps_clip": 0.2, "gamma": 0.99, "lr_actor": 3e-05, "lr_critic": 0.0001, "state_dim": 14400, "action_dim": 6, "K_epochs": 4, "action_std": 0.5, "has_continuous_action_space": false}}, 
  "Worldmodel": 
      {
      "image_size": (25, 24, 24),
      "scalar_size": 6,
      "latent_dim": 1024,
      "hidden_dim": 1024,
      }